# Generated by Django 3.2.7 on 2022-02-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created',
        ),
    ]
