# Generated by Django 3.2.7 on 2022-02-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookFavourite',
        ),
    ]
