# Generated by Django 3.2.7 on 2022-02-20 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_auto_20220220_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreviewrating',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
    ]
