# Generated by Django 3.2.7 on 2022-02-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_bookreviewrating_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookReviewRating',
        ),
    ]
